# **Практическое занятие 6: знакомимся с `numpy`**

## **План занятия**

- Обсуждение плана занятия
- Повторение лекции
- Самостоятельная работа + вопросы

# Модуль `numpy`

Перед работой с `numpy` его всегда необходимо импортировать:

In [1]:
import numpy as np

Основу `numpy` составляют `ndarray` &ndash; класс (тип) данных, в котором можно удобно хранить многомерные массивы данных. Их можно создать несколькими разными способами. Самый простой &ndash; из списка:

In [2]:
example = np.array([1, 2, 3, 4, 5, 6])
print(example, type(example))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


Другие способы создать массив (шаблоны):

In [3]:
print('Нолики: ')
print(np.zeros([3, 3])) # в качестве аргумента указываем СПИСОК с размером
                        # np.zeros(3, 3) не сработает!

print('ones:')
print(np.ones([3, 3]))

print('Arange с началом (1), концом (10) и шагом (0.1):')
print(np.arange(1, 10, 0.1))

Нолики: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange с началом (1), концом (10) и шагом (0.1):
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


`np.linspace` позволяет создавать массивы фиксированной длины (с равным промежутком между числами). Очень полезная функция:

In [7]:
print(np.linspace(0, np.pi, 100))

[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.7925268  2.824260

### Поэлементное умножение

- Если мы умножаем число на `ndarray`, то умножается весь массив. То же самое работает для всех других математических операций
- Если мы умножаем друг на друга `ndarray` **одинаковой длины**, то умножается каждый элемент одного массива на каждый элемент другого массива. Это же касается других математических операций.

Примеры:

In [5]:
a = np.arange(1, 10)
print('Умножаем массив на число:')
print(f'Массив a = {a}')
print(f'Массив a * 2 = {a*2}\n')

b = np.arange(1, 10)
print(f'Массив b = {b}')
print(f'Результат умножения a * b = {a*b}\n')

print(f'Результат сложения a + b = {a+b}\n')

print(f'Результат деления a/b = {a/b}')

Умножаем массив на число:
Массив a = [1 2 3 4 5 6 7 8 9]
Массив a * 2 = [ 2  4  6  8 10 12 14 16 18]

Массив b = [1 2 3 4 5 6 7 8 9]
Результат умножения a * b = [ 1  4  9 16 25 36 49 64 81]

Результат сложения a + b = [ 2  4  6  8 10 12 14 16 18]

Результат деления a/b = [1. 1. 1. 1. 1. 1. 1. 1. 1.]


Не получится перемножить массивы разной длины друг на друга:

In [40]:
array_len_10 = np.arange(10)
array_len_5 = np.arange(10)
array_len_10*array_len_5

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Мы можем узнать информацию о массивах с помощью следующих комманд:

In [9]:
print(f'Размер массива аrray_len_10 = {array_len_10.shape}') # размер массива
print(f'Длина массива аrray_len_10 = {len(array_len_10)}\n') # работает и функция len!

zeros = np.zeros([3, 3])
print(f'Матрица zeros: \n{zeros}')
print(f'Размер матрицы zeros = {zeros.shape}')

print(f'Количество измерений матрицы zeros = {zeros.ndim}') # то же самое что len(zeros.shape)

Размер массива аrray_len_10 = (10,)
Длина массива аrray_len_10 = 10

Матрица zeros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Размер матрицы zeros = (3, 3)
Количество измерений матрицы zeros = 2


## Базовое индексирование массивов `numpy`

Посмотрим на базовые примеры работы с матрицами и векторами. Индексирование вектора (одномерного массива) очень похоже на индексирование списков. А вот индексирование матриц немного отличается.

Синтаксис:
- `A[i, j]` - элемент в `i`-ой строчке и в `j`-ом столбце.
- `A[0, 0]` - элемент на строчке `0` и столбце `0`
- `A[:, 0]` - нулевой столбец
- `A[0, :]` - нулевая строчка

In [12]:
A = np.array([[1, 1, 1],
              [2, 2, 30],
              [3, 3 ,3]])

print(f'A[0, 0] = {A[0, 0]}')
print(f'Нулевой столбец: A[:, 0] = {A[:, 0]}')
print(f'Нулевая строчка: A[0, :] = {A[0, :]}')

A[0, 0] = 1
Нулевой столбец: A[:, 0] = [1 2 3]
Нулевая строчка: A[0, :] = [1 1 1]


# Семинарские задания и домашние задания (0.8 баллов)

## Здравствуйте почему у меня ошибка в коде

✅ **(0.05 балла)** Почему может быть ошибка в следующей ячейке?

In [2]:
import numpy as np
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


✅ **(0.075 балла)** А в этой?

In [3]:
example = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(example)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


✅ **(0.075 балла)** А с этой что не так?

In [4]:
print(np.zeros([3, 3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


✅ **(0.05 балла)** А тут-то чего не так....

In [5]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3 ,3]])
print(A.shape)

(3, 3)


✅ **(0.075 балла)** Да хватит уже блин когда это уже закончится помогите (найдите ошибку)

In [6]:
lat = np.arange(20, 40, 0.1)
lon = np.arange(-30, 30, 0.3)

print(np.sqrt(lat**2 + lon**2)) 

[36.05551275 35.86223641 35.67071628 35.48098082 35.29305881 35.10697936
 34.92277194 34.74046632 34.56009259 34.38168117 34.20526275 34.03086834
 33.85852921 33.68827689 33.5201432  33.35416016 33.19036005 33.02877533
 32.86943869 32.71238298 32.55764119 32.40524649 32.25523213 32.10763149
 31.962478   31.81980515 31.67964646 31.54203544 31.40700559 31.27459033
 31.144823   31.01773686 30.89336498 30.77174028 30.65289546 30.53686297
 30.42367499 30.31336339 30.20595968 30.10149498 30.         29.90150498
 29.80603966 29.71363323 29.62431434 29.53811098 29.4550505  29.37515957
 29.29846412 29.22498931 29.15475947 29.08779813 29.02412789 28.96377047
 28.90674662 28.85307609 28.80277764 28.75586897 28.71236667 28.67228627
 28.63564213 28.60244745 28.57271426 28.54645337 28.52367438 28.50438563
 28.48859421 28.47630594 28.46752536 28.46225571 28.46049894 28.46225571
 28.46752536 28.47630594 28.48859421 28.50438563 28.52367438 28.54645337
 28.57271426 28.60244745 28.63564213 28.67228627 28

### Ура данные

Выполните строчку ниже:

In [7]:
temps = np.loadtxt('data/temps.txt')
print(temps)

[[ 1.850e+03  1.000e+00 -7.710e-01 ...        nan        nan        nan]
 [ 1.850e+03  2.000e+00 -2.110e-01 ...        nan        nan        nan]
 [ 1.850e+03  3.000e+00 -3.670e-01 ...        nan        nan        nan]
 ...
 [ 2.023e+03  1.100e+01  1.401e+00 ...        nan        nan        nan]
 [ 2.023e+03  1.200e+01  1.425e+00 ...        nan        nan        nan]
 [ 2.024e+03  1.000e+00  1.299e+00 ...        nan        nan        nan]]


Это датасет, который я давал как один из примеров работы с проектами. Я немного обрезал его так, чтобы он удобно читался.

Он состоит из нескольких столбцов, разделенных пробелами. После считывания ее функцией `np.loadtxt` получаем матрицу размера `2089 x 12`:

In [8]:
x = temps.shape
x

(2089, 12)

✅ (**0.075 балла**) Сделайте новые переменные `year` и `month`, которые будут равные нулевому и первому столбцу данных соотвественно.

In [9]:
# Ваш код
year = temps[:, 0]  
month = temps[:, 1] 

print("Year:", year)
print("Month:", month)

Year: [1850. 1850. 1850. ... 2023. 2023. 2024.]
Month: [ 1.  2.  3. ... 11. 12.  1.]


✅ (**0.075 балла**) Мы могли бы запись дату вот так:


`time = year + month/12`

Таким образом, март 1871 будет `1871 + 3/12 = 1871.25`. Сделайте новую переменную `t` из двух столбцов `year` и `month`. `t.shape` должен быть равен `(2089,)` или `(2089, 1)`.

In [10]:
# Ваш код
t = year + month/12
print(t)
print(t.shape)

[1850.08333333 1850.16666667 1850.25       ... 2023.91666667 2024.
 2024.08333333]
(2089,)


### Ну это рандом

✅ **(0.1 балла)** Используя функцию `np.random.randn(100)` (число в скобках означает количество элементов в массиве) создайте массив из 100 случайных чисел и найдите среднее значение, минимальное и максимальное число в массиве. Вам пригодится гугл и [документация `numpy`](https://numpy.org/doc/1.26/reference/index.html#reference)

In [11]:
# Ваш код
randomizer = np.random.randn(100)
avg = (randomizer.sum()/100)
min_random = min(randomizer)
max_random = max(randomizer)
print('Сам рандом:', randomizer)
print('Среднее:', avg)
print('Минимальное:', min_random)
print('Максимальное:',max_random)

Сам рандом: [ 0.03314766 -0.68975286 -1.6281469  -1.30078971 -1.55726117  0.30324329
  0.37879901 -0.25024758 -0.94689464 -0.71325563  0.44954664  0.85428719
 -0.85767963 -0.19365709 -1.00894074  1.00930198  0.11833222  0.61887983
  1.17415869 -0.26829509  0.49948654 -0.26866607  0.74683208 -0.35676187
 -0.15283761  0.00250029  0.33259062 -0.18287729  1.42476157  1.4710508
  0.2324337  -0.18892601 -0.89473347  1.66837667 -0.06828091 -0.61057224
 -1.15682444 -0.23638327  0.88326138  0.13427285 -0.46899744 -0.84948118
 -1.02917527  0.65022494 -1.09060995  0.60888311  0.47493977 -0.0909211
  0.34929389  0.76863792 -0.29955284 -1.8232483   0.93347288 -0.60201805
 -1.04002522  0.85016445 -1.32667868 -0.56649937 -0.41068563 -0.79057159
  0.49946929  0.20631726  1.94809434 -0.11269881  2.19555669  0.09321531
  0.40805218  0.21029469  1.58129644 -0.07945058  1.00082372 -0.62698162
 -0.04939416 -0.77086893  1.80584844  0.48954171  0.9441541   0.21484442
  0.82751304  0.11205985  0.39258891  0.8

### ✨ Ну кто там у тебя краш

✅ **(0.075 балла)** Сделайте вектор из 100 значений от `0` до `5`:

In [12]:
# Ваш код
heh = np.linspace(0, 5, 100)
print(heh)

[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3.53535354 3.58585859
 3.63636364 3.68686869 3.73737374 3.78787879 3.83838384 3.88888889
 3.93939394 3.98989899 4.04040404 4.09090909 4.14141414 4.19191919
 4.24242424 4.29292929 4.34343434 4.39393939 4.44444444 4.4949

✅ **(0.1 балла)**  Попробуйте посчитать вашу любимую функцию (если у вас нет любимой функции, то ~~пересмотрите ваши взгляды на жизнь~~ посчитайте, например, $y = \sqrt{x}$):

In [13]:
# Ваш код
y = heh**3
print(y)

[0.00000000e+00 1.28826269e-04 1.03061015e-03 3.47830926e-03
 8.24488122e-03 1.61032836e-02 2.78264741e-02 4.41874103e-02
 6.59590497e-02 9.39143501e-02 1.28826269e-01 1.71467764e-01
 2.22611793e-01 2.83031313e-01 3.53499282e-01 4.34788658e-01
 5.27672398e-01 6.32923460e-01 7.51314801e-01 8.83619379e-01
 1.03061015e+00 1.19306008e+00 1.37174211e+00 1.56742922e+00
 1.78089434e+00 2.01291045e+00 2.26425050e+00 2.53568745e+00
 2.82799426e+00 3.14194388e+00 3.47830926e+00 3.83786338e+00
 4.22137918e+00 4.62962963e+00 5.06338768e+00 5.52342628e+00
 6.01051841e+00 6.52543700e+00 7.06895503e+00 7.64184545e+00
 8.24488122e+00 8.87883529e+00 9.54448062e+00 1.02425902e+01
 1.09739369e+01 1.17392938e+01 1.25394337e+01 1.33751297e+01
 1.42471547e+01 1.51562817e+01 1.61032836e+01 1.70889334e+01
 1.81140040e+01 1.91792685e+01 2.02854996e+01 2.14334705e+01
 2.26239541e+01 2.38577232e+01 2.51355510e+01 2.64582103e+01
 2.78264741e+01 2.92411154e+01 3.07029070e+01 3.22126221e+01
 3.37710335e+01 3.537891

### ✨ Нормально все? 

✅ **(0.15 балла)** Используя:
```python
mu = 0
sigma = 1
```
и функцию `np.exp(x)` (это означает $e^{x}$) запишите формулу при `x` от `-5` до `5`:
$$\Large \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}$$

Эта функция называется [функцией Гаусса](https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D1%83%D1%81%D1%81%D0%BE%D0%B2%D0%B0_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F), mu &mdash; среднее значение этой функции, а sigma &mdash; стандартное отклонение. 

In [14]:
# Ваш код
x = np.arange(-5,5)
mu = 0
sigma = 1
y = (1/(np.sqrt(2*np.pi*sigma**2)))* np.exp(-((x-mu)**2)/(2*sigma**2))
y

array([1.48671951e-06, 1.33830226e-04, 4.43184841e-03, 5.39909665e-02,
       2.41970725e-01, 3.98942280e-01, 2.41970725e-01, 5.39909665e-02,
       4.43184841e-03, 1.33830226e-04])

✅ ✨ **(0.15 балла)** Используя [формулу оценки дисперсии случайной величины](https://ru.wikipedia.org/wiki/%D0%94%D0%B8%D1%81%D0%BF%D0%B5%D1%80%D1%81%D0%B8%D1%8F_%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B9%D0%BD%D0%BE%D0%B9_%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B8%D0%BD%D1%8B): 
$$S = 1/n\sum(X - mean(X))^2$$
где `mean` &mdash; среднее массива, `n` &mdash; количество элементов в массиве, `X` &mdash; массив случайных чисел, найдите дисперсию полученного массива.


In [16]:
# Ваш код
massiv = np.random.random(100)
mean = (massiv.sum()/len(massiv))
n = len(massiv)
s = (1/n)*(sum((massiv - mean)**2))
print(massiv, s)

[0.51806307 0.93456329 0.98546347 0.09843387 0.07504819 0.66554058
 0.68403683 0.8336039  0.21801637 0.1557685  0.31772708 0.05035461
 0.71843865 0.84113203 0.7120952  0.55821023 0.72769222 0.04148228
 0.78763727 0.58347028 0.71960676 0.70636462 0.34047419 0.35659229
 0.21169867 0.42444627 0.16822231 0.74688158 0.63782098 0.46322388
 0.42563379 0.74053226 0.91180083 0.13547766 0.85916399 0.5951518
 0.85986256 0.57098686 0.68601709 0.05567568 0.3762243  0.17370361
 0.1574599  0.7358567  0.91480841 0.54441481 0.79626234 0.395885
 0.65575326 0.5857211  0.33462942 0.1279203  0.60161919 0.8316174
 0.45314113 0.60941306 0.55518446 0.16936697 0.32058604 0.34606025
 0.17680889 0.20363167 0.14812527 0.33369096 0.04822757 0.02688891
 0.47898849 0.65060731 0.27898037 0.08999407 0.32993985 0.33139267
 0.67280137 0.33581173 0.60499631 0.48651814 0.50946231 0.31072739
 0.19742884 0.14963784 0.08884714 0.0046862  0.82709879 0.64492265
 0.50146399 0.11225177 0.97897238 0.38517842 0.74187082 0.72330626

**Комментарий: наверное в задании имелось в виду посчитать S для гауссовой функции из прошлого пункта, но в целом `np.random.randn()` это почти оно же поэтому сойдёт**

###  ✨ Память поколений

**(0.2 балла)** Придумайте задачку для домашнего задания или семинара для следующих поколений студентов ФГГТ!

- Задачи должны быть оригинальными или существенно видоизмененными (и точно не должны гуглиться)
- Языковые модели использовать нельзя
- Хихи-хаха поощряются, но все хорошо в меру
- В задачке должна быть указано для какой она недели (от первой до пятой)
- Задачка должна быть на тему лекции, в ней не должны использоваться констукции `python` вне курса или из следующих лекций
- Задачка должна прилагаться с решением

In [11]:
# Ваша задачка

### ✨ Триангулируем портал в энд

В компьютерной игре `minecraft` используется весьма оригинальный способ нахождения портала в измерение края (`End dimension`): игрок должен запустить [око края](https://ru.minecraft.wiki/w/%D0%9E%D0%BA%D0%BE_%D0%9A%D1%80%D0%B0%D1%8F), оно полетит вверх и в сторону портала и немного зависнет в воздухе. Игрок должен запомнить куда оно полетело, и двигаться в сторону портала запуская `ока края` до тех пор, пока они не изменят своего направления, показывая уже вниз.

Впрочем, известно, что можно найти портал и более хитрым способом: запустить два `ока края` находясь на некотором удалении друг от друга. Зная точные координаты запуска и угол полета ока с помощью [экрана отладки](https://ru.minecraft.wiki/w/%D0%AD%D0%BA%D1%80%D0%B0%D0%BD_%D0%BE%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8) можно получить точные координаты с помощью теоремы косинусов. Более подробно с формулами в [этом видео](https://www.youtube.com/watch?v=hAKY7XyZqOo). Такой процесс называется триангуляцией и может часто использоваться физике/географии.

**(0.2 балла)** Помогите легендарному игроку `popbob`-у найти портал в измерение края. Находясь в координатах `(0, 0)` (x, z) он запустил око края и получил угол в `109.9` градусов, отошел в координаты `(-350, 0)`, запустил еще одно око края и получил угол в `115` градусов (координаты как в видео выше). Помогите ему найти точные координаты портала!

In [ ]:
# Ваш код


**(0.1 балла)** Напишите и **(0.1 балла)** продокументируйте функцию для поиска портала.

In [ ]:
# Ваш код

### Infamous griefer popbob
✨✨✨ **(Без балла)** В давние времена, легендарный игрок `popbob` на старейшем анархо-сервере в майнкрафте `2b2t` [триангулировал местоположение игроков по звуку грома](https://www.youtube.com/watch?v=T2H527m60bQ). Однако навестись на звук грома гораздо сложнее, чем на местоположение ока края, поэтому представим, что у нас есть погрешность в `+- 5 градусов`. Помогите ему найти точки, в которых могут находится игроки:

In [ ]:
# Ваш код

✨✨✨✨✨ **(Без балла)** Что будет, если описывать погрешность угла вероятностным нормальным распредлением с полушириной в `5 градусов`?

In [ ]:
# Ваш код

### Редкая гадость

✨✨✨ (**Без балла**) Реализуйте [метод Гаусса](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%93%D0%B0%D1%83%D1%81%D1%81%D0%B0) с помощью `numpy`. 

In [ ]:
# Ваш код